title: Lam Dinh
description: AI & ML Engineer | Smart Surveillance | Deep Learning
theme: jekyll-theme-cayman

defaults:
  -
    scope:
      path: ""
    values:
      stylesheets: [assets/style.css]
